---
format: 
  pdf: 
    documentclass: article
    geometry:
      - top=10mm
      - left=15mm
      - right=15mm
      - bottom=5mm
      - heightrounded
    fontfamily: libertine
    colorlinks: true
    fontsize: '16'
    include-in-header: 
      text: |
        \usepackage{multicol}
        \usepackage{lipsum}
        \usepackage{hyperref}
        \usepackage{libertine}
        \pagestyle{empty}
        \setlength{\multicolsep}{2pt plus 1.0pt minus 0.75pt}% 50% of original values
        \setlength{\columnsep}{3em}
        
    header-includes:
      - \usepackage{enumitem}
      - \setlist[itemize]{noitemsep, topsep=0pt, left=0pt}
---

<!-- TITLE -->

\begin{huge}\begin{center}{\bf JESUS RODRIGUEZ}\end{center}\end{huge}

<!-- CONTACT INFO -->

\begin{center}jrodriguezb44@gmail.com ∙ \href{https://www.linkedin.com/in/jesus-rodriguez-09ab12178}{LinkedIn} ∙ Lincoln, NE
\end{center}
\vspace{3.5pt}

<!-- EDUCATION: 1ST BULLET -->

\begin{large}
  {\bf EDUCATION}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf University of Nebraska-Lincoln}\end{flushleft}
    \begin{flushright}Graduation Date-Dec 2025\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}Bachelor's in Statistics and Data Analytics\end{flushleft}
    \begin{flushright}Lincoln, NE\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}Minor in Mathematics\end{flushleft}
  \end{multicols}
\end{large}

\vspace{0.05cm}

<!-- RELEVANT EXPERIENCE : 1ST BULLET-->

\begin{large}{\bf RELEVANT EXPERIENCE}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://www.utmb.edu/spph/department/of-biostatistics-data-science/programs-training/summer-institute}{University of Texas-Medical Branch}}\end{flushleft}
    \begin{flushright}June 2025-July 2025\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Summer Intern of Biostatistics and Data Science}\end{flushleft}
    \begin{flushright}Galveston, TX\end{flushright}\end
  {multicols}
\end{large}
\vspace{-0.16cm}

-   Cooperated with biostatisticians, principal investigators, and doctoral researchers to examine clinical burn patient data from TriNetX to better treat burn scarring; ultimately ran a chi-square analysis in R to find an association between patient age and burn size for certain outcomes
-   Attended lectures related to advanced statistical methods such as linear regression, mixed models, and machine learning methods
-   Presented research analysis findings, translating statistical tables and charts into clear, actionable insights for both technical and non-technical audiences
-   Documented data, methodologies, and interpretation of findings to help author research manuscripts

\vspace{3pt}

<!-- RELEVANT EXPERIENCE : 2ND BULLET -->

\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://globalcareeraccelerator.org}{The Global Career Accelerator}}\end{flushleft}
    \begin{flushright}Jan 2025-Dec 2025\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Data Analyst and Coding for Data Intern}\end
    {flushleft}\begin{flushright}Remote\end
    {flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}

-   **Fall 2025 (SQL and Python):**

    -   Hands on experience learning SQL and Python, guided by professionals

-   **Spring 2025 (Excel and Tableau):**

    -   Analyzed A/B tests to measure understanding of trends and audience behavior for The Recording Academy in Excel using pivot tables and logical functions such as Xlookup

    -   Told a story with data by generating visualizations for Intel's Sustainability team in Tableau utilizing charts and dashboards

\vspace{3pt}

<!-- OTHER WORK EXPERIENCE : 1ST BULLET -->

\begin{large}{\bf OTHER WORK EXPERIENCE}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{http://www.yorkanimalclinic.com}{York Animal Clinic}}\end{flushleft}
    \begin{flushright}May 2018-Present\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Veterinary Assistant}\end
    {flushleft}\begin{flushright}York, NE\end
    {flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}

-   Communicated and partnered effectively with veterinarians and veterinary technicians to guarantee thorough understanding of patients' needs
-   Adapted quickly to changing priorities, worked efficiently under pressure, and collaborated with team members to provide ample care and compassion to both patients and clients

\vspace{3pt}

<!-- SKILLS -->

\begin{large}{\bf SKILLS}
  \vspace{3pt}
  \hrule
\end{large}
\vspace{-0.16cm}

**Technical** - Statistical modeling (linear/logistic regression, ANOVA), experimental design, power analysis, data management (dplyr, pandas), data visualization (ggplot2, matplotlib), reproducible reporting (Quarto, R Markdown), version control (Git/GitHub), database querying (SQL)

<!-- **Interpersonal** - Communication, Collaboration, Adaptability, Detail-oriented, Problem-solving -->

**Languages and Tools** - *proficient:* R, SAS, Excel, Tableau *intermediate:* SQL, Git/Github, Python

**Selected Coursework** - Principles of Statistical Design I & II, Principles of Statistical Analysis, Statistical Computing in R and Python I & II, Statistical Modeling I & II, Analysis of Messy Data, Technical Statistician Skills, Regression Analysis, Calculus I, II, & III, Linear Algebra, Differential Equations

<!-- INVOLVEMENT : 1ST BULLET -->

\begin{large}{\bf INVOLVEMENT}
  \vspace{3pt}
  \hrule  
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://statistics.unl.edu/sc3lhelp-desk}{Statistical Cross-disciplinary Collaboration and Consulting Lab}}\end{flushleft}
    \begin{flushright}Jan 2025-May 2025\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{R and SAS Trainee}\end
    {flushleft}\begin{flushright}Lincoln, NE\end
    {flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}

-   Participated in a statistical analysis workshop using R and SAS, applying hypothesis testing methods such as t-tests and ANOVA, as well as data wrangling and visualization techniques to datasets
-   Completed guided exercises analyzing datasets with R and SAS, reinforcing statistical concepts and reproducible reporting

\vspace{3pt}
